name: Build APK

on: 
  push:
    branches: main

jobs:
  build:
    name: Build APK and Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.0'

    - run: flutter pub get

    - run: flutter build apk --release --split-per-abi
    
    - run: flutter build appbundle
    
    - run: flutter build apk
      
    - uses: actions/upload-artifact@v1
      with:
        name: Upload AAB
        path: build/app/outputs/bundle/release/app-release.aab
        
    - uses: actions/upload-artifact@v1
      with:
        name: Upload APK
        path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
    
    - uses: actions/upload-artifact@v1
      with:
        name: Upload fat APK
        path: build/app/outputs/apk/release/app-release.apk
